### ISSUE TITLE
Join Mattermost integrations community channel?

### ISSUE THREAD

**Issue by jasonblais** [ldziedziul/matterbook#1]
Hi @ldziedziul,

Thank you for sharing your project with us, great work with the Matterbook integration! 

We'd also like to welcome you to join the [integrations community channel on our nightly builds server](https://pre-release.mattermost.com/core/channels/integrations), if you'd like and haven't yet.

Wonderful work! Can't wait to share it with the rest of the Mattermost community!

PS: thank you for [contributing to the desktop community](https://github.com/mattermost/desktop/pull/324#issuecomment-250451797) as well, your help is much appreciated.

**Comment by ldziedziul** [comment]
Thanks, I've already joined your channel :)
