### ISSUE TITLE
why this error occur?

### ISSUE THREAD

**Issue by taeilseok** [ldziedziul/matterbook#2]
I have set a matter.yml follow your guide and run for matterbok-run.sh script.
## But below error occurred.

Traceback (most recent call last):
  File "./matterbook.py", line 137, in <module>
    main()
  File "./matterbook.py", line 28, in main
    check_posts(graph, config)
  File "./matterbook.py", line 56, in check_posts
    last_post_text = last_post['message'].encode("utf8")
KeyError: 'message'

---

what's wrong on this situation?

**Comment by ldziedziul** [comment]
I'm currently travelling so I'll probably check this tomorrow. My rough guess would be that there is a problem with your Facebook api key.

**Comment by taeilseok** [comment]
## I'm get user_access_token in this way 

![image](https://cloud.githubusercontent.com/assets/22041663/19625695/a141064a-995a-11e6-9e4f-f1ef2eb96794.png)

that is wrong way to get api key?

**Comment by ldziedziul** [comment]
It wasn't a problem with the Facebook API. This error occurs when the last post from the checked page doesn't contain any text (e.g. only an image). Let me if it's working for you.

**Comment by taeilseok** [comment]
Yes, and another encode error was occured then i'm change to code this way 

---

In the 57 lines in mattermost.py
post_filter = integration.get('fb_post_filter').encode("utf8") -->
post_filter = integration.get(('fb_post_filter').encode("utf8"))

---

And looks great work.
![image](https://cloud.githubusercontent.com/assets/22041663/19669628/d803bc3a-9a9b-11e6-8ade-2f4438345bcf.png)

**Comment by ldziedziul** [comment]
I'm very surprised that you need such change. Could you drop me error details before your change?

**Comment by ldziedziul** [comment]
I'm guessing you didn't set fb_post_filter. My latest commit (08ffa9d9351ee397fbb620d728a9da85218595ae) should fix it.
